### ISSUE TITLE
Buy supplies for May 17 kickoff party

### ISSUE THREAD

**Issue by sandover** [sandover/kraken#13]
- [ ] LED lights (selected: pixie)
- [ ] 3 and 4 foot balloons
- [ ] light strips
- [ ] wire (22 and 16)
- [ ] tank of helium
- [ ] power supply (spark fun inventor kit sufficient?)
- [ ] multimeter

**Comment by gkhadge** [comment]
ELECTRONICS SUPPLIES

3W RGB LEDs:
https://www.adafruit.com/product/2741
http://ytai-mer.blogspot.com/2015/11/pixie-bright-things-come-in-small.html

5V (1 or 2 amp min) Power supply:
jank-wire it from a USB phone charger?

breadboard + arduino thing
Brandon has this
I might be able to dig up some stuff too

multimeter
-Brandon has this

Wiring
-Brandon's getting this. 
-22 gauge for digital
- 16 gauge or lower for power and ground

**Comment by sandover** [comment]
3 pixies should arrive by Friday. 

The spark fun inventor's kit comes with a power supply, can you have a look at it?  https://www.sparkfun.com/products/14684

**Comment by gkhadge** [comment]
https://cdn.sparkfun.com/datasheets/Wireless/WiFi/PhotonRedboardV1.pdf
500 mA max output current from the 5V output. We're gonna want closer to 2A or more.
