### ISSUE TITLE
Find Brandon accommodations for burning man

### ISSUE THREAD

**Issue by sandover** [sandover/kraken#20]
Options: 
- trailer
- RV
- shiftpod
- hexayurt

**Comment by jessicakim0729** [comment]
Are you open to stay in a hotel?

**Comment by sandover** [comment]
It's going to be a hexayurt.

**Comment by jessicakim0729** [comment]
So.... you found a place??

**Comment by sandover** [comment]
I am going to buy Phoenix & Brehon's hexayurt!

http://hexayurt.com/

http://azburners.org/files/Building-Hexayurts.pdf
