### ISSUE TITLE
Plan party 

### ISSUE THREAD

**Issue by ghost** [sandover/kraken#60]
Brandon to talk to Jonathan Hinton re spearheading setup and party organizing and connect him with Lali.

Questions/Tasks:
-Evite or Eventbrite or FB event or ?
-Make blog post
-How much to charge for tickets
-Time of party (after 8pm)
-DJ
-Sound system
-Other entertainment?
-Ask Pollysuperstar for undersea decor from previous kinky salon
-Setup paypal for other donations 
-Other ways to get people to donate beyond ticket cost?

**Comment by sandover** [comment]
Next action: Brandon talk to Jonathan Hinton.

**Comment by sandover** [comment]
pinged jonathan today via text

**Comment by ghost** [comment]
Phoenix talked to Kismet re Burner costuming sale at party for additional donations and discussed possibility of vendors with partial donation (30%?)(in Kismet's case this would be cuffs and collars). To discuss with Brandon

**Comment by sandover** [comment]
create a new board specifically for planning party, jump to https://github.com/sandover/kraken/projects/11
