### ISSUE TITLE
Phoenix poke people to activate GitHub:

### ISSUE THREAD

**Issue by ghost** [sandover/kraken#61]
Linden
Liz
Illona

**Comment by sandover** [comment]
I poked Linden this morning. I want him to join so we can assign the balloon chain issue to him.

**Comment by ghost** [comment]
Poked Liz and Illona. Wanting to add robatomy@gmail.com (my contractor, Robert, who wants to help in LA who I mentioned to you). How do I create a new invitation?

**Comment by sandover** [comment]
(I see that he signed up for the newsletter.)
In github, go to Settings tab => Collaborators.  Can invite by email or github handle.

**Comment by ilona-ska** [comment]
I'm here.

**Comment by sandover** [comment]
@ilona-ska, that's funny, github still thinks this:

<img width="982" alt="image" src="https://user-images.githubusercontent.com/224739/59944138-dd092200-9418-11e9-8c53-9b6714ef6e47.png">

Anyway, hi! :)

**Comment by sandover** [comment]
I've also asked Rob Gonnella.
