### ISSUE TITLE
Brandon meeting with Jessica 

### ISSUE THREAD

**Issue by ghost** [sandover/kraken#62]
-Aesthetic vision

**Comment by sandover** [comment]
Met with @tiggrum last night and talked through aesthetic vision for the project.  Next steps: Jessica will pinterest at me, I will respond, and we will work toward concrete decor ideas.

Also: I will talk to Liz about ideas for combining light housing with danging fiber optic cable.

@tiggrum : can you propose some specific fiber optic material to prototype with?

**Comment by sandover** [comment]
trimming some scope from this issue and creating a new issue purely for june 30 work party planning.
