### ISSUE TITLE
Kickoff call

### ISSUE THREAD

**Issue by sandover** [sandover/kraken#75]
Goals for the call

- determine price
- determine how to charge
- what ticketing means to use (eventbrite?)
- assign board tasks to people
- determine time of party

**Comment by ghost** [comment]
Invite to Zoom meeting:
Jessica Westbrook (can do between 3pm and 6pm Weds)
Lali (Phoenix texted, waiting to hear back)
Jonathan Hinton (can do between 3pm and 6pm Weds)
Brandon (3pm-6pm ideal Tues and Weds)
Phoenix (3pm-5pm Tues, 3pm-6pm Weds)

**Comment by ghost** [comment]
Phoenix left a voicemail for Lali, in addition to texting 6/24. Waiting to hear back to finalize Zoom meeting time for Wednesday.

**Comment by tiggrum** [comment]
You may want Linden in on this convo. He’s got a better handle on profiting from events than I do.

**Comment by ghost** [comment]
Just tagged him about it on Slack. Once Lali gets back to me to confirm time (I left a second voicemail and text today), I'll send all of you a specific time and loop Linden in

**Comment by sandover** [comment]
Call done!  Moving to the pile of dead soldiers.
